### ISSUE TITLE
Add submodule support

### ISSUE THREAD

**Issue by gutenye** [actions/zeit-now#8]

**Comment by peaceiris** [comment]
Try the following. It will work well.

```yaml
- uses: actions/checkout@master
  with:
    submodules: true
```

checkout/action.yml - actions/checkout: https://github.com/actions/checkout/blob/94d077c24971944d312dd9197c1bdfba62b39878/action.yml#L13
